
export const CUSTOMER_ADD = 'CUSTOMER_ADD';
export const CUSTOMER_REMOVE = 'CUSTOMER_REMOVE';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_SEARCH = 'CUSTOMER_SEARCH';
export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMERS';
export const GET_CUSTOMERS_BY_ID = 'GET_CUSTOMERS_BY_ID';